- hosts: all
  connection: local
  tasks:
    - name: remove "user-data" file
      delegate_to: localhost
      blockinfile:
        path: /Volumes/system-boot/user-data
        block: ""

    - name: copy "user-data" file
      delegate_to: localhost
      blockinfile:
        path: /Volumes/system-boot/user-data
        block: |
          #cloud-config
          # Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
          hostname: {{ ansible_host }}
          manage_etc_hosts: true

          write_files:
          - path: /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
            permissions: '0644'
            content: |
              network: {config: disabled}

          - path: /etc/netplan/my-new-config.yaml
            permissions: '0644'
            content: |
              network:
                version: 2
                wifis:
                  wlan0:
                    access-points:
                      "{{ hostname }}":
                        password: "{{ password }}""
                    dhcp4: no
                    addresses:
                      - "{{ ansible_host }}/24"
                    gateway4: 10.0.0.1
                    nameservers:
                        addresses: [75.75.75.75]

          runcmd:
           - rm /etc/netplan/50-cloud-init.yaml
           - netplan generate
           - netplan apply
