- hosts: all
  connection: local
  tasks:
    - name: allow ssh
      copy:
        content: ""
        dest: /Volumes/system-boot/ssh

    - name: Remove "user-data" file
      ignore_errors: yes
      ansible.builtin.file:
        path: /Volumes/system-boot/user-data
        state: absent

    - name: Remake "user-data" file
      blockinfile:
        create: true
        path: /Volumes/system-boot/user-data
        block: |
          #cloud-config
          hostname: {{ hostname }}
          manage_etc_hosts: true
          timezone: America/New_York

    - name: Remove "network-config" file
      ignore_errors: yes
      ansible.builtin.file:
        path: /Volumes/system-boot/network-config
        state: absent

    - name: remake "network-config"
      blockinfile:
        create: true
        path: /Volumes/system-boot/network-config
        block: |
          network:
            version: 2
            ethernets:
              eth0:
                dhcp4: true
                optional: true
            wifis:
              wlan0:
                optional: true
                access-points:
                  "{{ ssid }}":
                    password: "{{ password }}"
                dhcp4: false
                addresses:
                  - {{ ansible_host }}/24
                gateway4: 10.0.0.1
                nameservers:
                  addresses: [75.75.75.75]
