- hosts: all
  connection: local
  tasks:
    - name: allow ssh
      copy:
        content: ""
        dest: /Volumes/system-boot/ssh

    - name: Remove "user-data" file
      ignore_errors: yes
      ansible.builtin.file:
        path: /Volumes/system-boot/user-data
        state: absent

    - name: Remake "user-data" file
      copy:
        dest: /Volumes/system-boot/user-data
        content: |
          #cloud-config
          hostname: {{ hostname }}
          manage_etc_hosts: true
          packages:
          - avahi-daemon
          apt:
            conf: |
              Acquire {
                Check-Date "false";
              };

          users:
          - name: worker
            groups: users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render,sudo
            shell: /bin/bash
            lock_passwd: false
            passwd: $5$RZjH.xQeAE$4kBTav9zc7V4OpoF/Hg8ZdCEAH34O2Tofotn1S5WPQA

          ssh_pwauth: true

          timezone: America/New_York
          runcmd:
          - localectl set-x11-keymap "us" pc105
          - setupcon -k --force || true

    - name: Remove "network-config" filessh
      ignore_errors: yes
      ansible.builtin.file:
        path: /Volumes/system-boot/network-config
        state: absent

    - name: remake "network-config"
      copy:
        dest: /Volumes/system-boot/network-config
        content: |
          version: 2
          ethernets:
            eth0:
              dhcp4: no
              addresses:
                - {{ ansible_host }}/24  # Replace with your desired static IP
              gateway4: 10.0.0.1
              nameservers:
                addresses: [75.75.75.75, 75.75.75.76]
